version: '3.8'

services:
  build:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: >
      sh -c "cargo build --release --target x86_64-unknown-linux-gnu && cargo build --release --target aarch64-unknown-linux-gnu"

  upload:
    build:
      context: .
      dockerfile: Dockerfile.upload
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: sh upload.sh