version: "3.8"
services:
  build_x86_64:
    build:
      context: .
      dockerfile: Dockerfile.x86_64
    volumes:
      - ./target:/app/target

  build_aarch64:
    build:
      context: .
      dockerfile: Dockerfile.aarch64
    volumes:
      - ./target:/app/target
