name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Verify Docker Compose installation
      run: docker-compose --version

    - name: Build and push Docker image
      run: docker-compose up --build

    - name: Install Cross
      run: cargo install cross

    - name: Compile Binary for x86_64
      run: cross build --release --target x86_64-unknown-linux-gnu

    - name: Compile Binary for aarch64
      run: cross build --release --target aarch64-unknown-linux-gnu

    - name: Install GitHub CLI
      run: |
        sudo apt-get install -y gh

    - name: Authenticate GitHub
      run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token

    - name: Generate Build Status Report
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./generate_report.sh

    - name: Upload Build Status Report
      uses: actions/upload-artifact@v4
      with:
        name: build-report
        path: build_report.html


        #check changes

        #made changes to ownsership